# .github/workflows/generate-index.yml
#
# This workflow uses a template file (_template.txt) to generate a dynamic
# and polished index.html file. It runs on the 'debug' branch for safe testing.

name: Generate Index Page

on:
  push:
    branches:
      - debug
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Index from Template
        run: |
          # Create a temporary file to hold the latest projects HTML
          LATEST_PROJECTS_HTML_FILE=$(mktemp)
          # Get the 5 most recently committed HTML files, format them as cards, and save to the temp file
          for file in $(git log -5 --name-only --pretty=format: -- '*.html' | grep -v "index.html" | awk '!a[$0]++'); do
            title=$(echo "$file" | sed 's/\.html$//; s|/| : |g; s/-/ /g; s/_/ /g; s/\b\(.\)/\u\1/g')
            echo "<div class='project-card' data-title='${title} ${file}'><a href='/${file}'>${title}</a><span class='path'>/${file}</span></div>" >> $LATEST_PROJECTS_HTML_FILE
          done

          # Create a temporary file to hold the JSON array of all project paths
          ALL_PROJECTS_JSON_FILE=$(mktemp)
          # Find all HTML files, format as a comma-separated list of strings, and save to the temp file
          find . -type f -name "*.html" ! -name "index.html" -printf '"%p",\n' | sed 's|^\./||' | sort | tr -d '\n' | sed 's/,$//' > $ALL_PROJECTS_JSON_FILE
          
          # Use sed to replace placeholders in the template with content from our temp files
          # 1. Start with a copy of the template
          cp _template.txt index.html
          # 2. Atomically replace both placeholders in the new index.html file
          sed -i \
            -e "/%%LATEST_PROJECTS%%/r $LATEST_PROJECTS_HTML_FILE" -e "s/%%LATEST_PROJECTS%%//" \
            -e "/%%ALL_PROJECTS_JSON%%/r $ALL_PROJECTS_JSON_FILE" -e "s/%%ALL_PROJECTS_JSON%%//" \
            index.html

      - name: Commit and Push Index
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate dynamic index.html from template"
          file_pattern: index.html
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
