name: Generate Index Page

on:
  push:
    branches:
      - debug
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate index.html
        run: |
          LATEST_PROJECTS_HTML_FILE="index.html"
          echo "<!DOCTYPE html><html><head><title>Projects</title></head><body>" > $LATEST_PROJECTS_HTML_FILE
          echo "<h1>Projects</h1>" >> $LATEST_PROJECTS_HTML_FILE
          find . -name "*.html" ! -name "index.html" | sort | while read file; do
            title=$(echo "$file" | sed 's/\.html$//; s|/| : |g; s/-/ /g; s/_/ /g; s/\b\(.\)/\u\1/g')
            echo "<div class='project-card' data-title='${title} ${file}'><a href='/${file}'>${title}</a><span class='path'>/${file}</span></div>" >> $LATEST_PROJECTS_HTML_FILE
          done
          ALL_PROJECTS_JSON_FILE=$(mktemp)
          find . -name "*.html" ! -name "index.html" | sed 's|^\./||' | jq -R . | jq -s . > $ALL_PROJECTS_JSON_FILE
          echo "<script>var allProjects = " > all-projects.js
          cat $ALL_PROJECTS_JSON_FILE >> all-projects.js
          echo ";</script>" >> all-projects.js
          echo "<script src='all-projects.js'></script>" >> $LATEST_PROJECTS_HTML_FILE
          echo "</body></html>" >> $LATEST_PROJECTS_HTML_FILE

      - name: Commit index.html
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: index.html
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: build-index
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
